name: Fact
main: com.github.LeoVerto.Fact.Fact
version: 0.0.1

commands:
  fact:
    description: Share a fact with other players.
    usage: /fact [message]
    permission: fact.fact
    permission-message: You don't have fact.fact