name: Fact
main: com.github.LeoVerto.Fact.Fact
version: 0.3.2
author: LeoVerto

commands:
  fact:
    description: Share a fact with other players.
    usage: /<command> [message]
    permission: fact.fact
    permission-message: You don't have permission!
    
permissions:
  fact.fact:
    description: Allows use of /fact
    default: true
  fact.receive:
    description: Allows seeing new facts
    default: op
  fact.ignore:
    description: Allows use of /fact ignore
    default: true
  fact.reload:
    description: Allows use of /fact reload
    default: op
