name: Fact
main: io.github.LeoVerto.Fact.Fact
version: 0.3.5
author: LeoVerto
dev-url: http://dev.bukkit.org/server-mods/fact/

commands:
  fact:
    description: Share a fact with other players.
    usage: |
      /<command> <message> - Send out a fact
      /<command> ignore - Do not display future facts until run again
      /<command> reload - Reload plugin
    
permissions:
  fact.fact:
    description: Allows use of /fact
    default: true
  fact.receive:
    description: Allows seeing new facts
    default: true
  fact.ignore:
    description: Allows use of /fact ignore
    default: true
  fact.reload:
    description: Allows use of /fact reload
    default: op
  fact.spy:
    description: See who wrote a fact
    default: op

